-- Simple Hive Program

-- load data from s3 source
-- specify variable names

CREATE TABLE wdi (Country STRING,Survival_to_65_female INT,Survival_to_65_male INT,Pop_0_14 INT,Pop_15_64 INT,Pop_65_up INT)
    ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE;

LOAD DATA INPATH 's3://bigdatabucket123/wdi_extract.csv'
    OVERWRITE INTO TABLE wdi;

-- queries

SELECT Country FROM wdi;

SELECT Country, Pop_65_up FROM wdi
    SORT BY Pop_65_up DESC; 
